export const menus = [
  {
    title: "แดรชบอร์ด",
    icon: "pi pi-home",
    name: "dashboard",
    to: "/",
    children: [],
  },
  //Report start
  {
    title: "รายงาน",
    icon: "pi pi-file",
    to: "",
    name: "report",
    children: [
      {
        title: "รายงานสินค้าคงเหลือ",
        icon: "pi pi-file",
        to: "/report/balance",
        name: "balance",
        children: [],
      },
      {
        title: "รายงานขาย",
        icon: "pi pi-file",
        to: "/report/salereport",
        name: "salereport",
        children: [],
      },
      {
        title: "รายงานสินค้า",
        icon: "pi pi-file",
        to: "/report/product",
        name: "productreport",
        children: [],
      },
      //Report addnew
      {
        title: "รายงานรายละเอียดสินค้า",
        icon: "pi pi-file",
        to: "/report/productdetailreport",
        name: "productdetailreport",
        children: [],
      },
      {
        title: "รายงานรายละเอียดสินค้า ตามกลุ่ม",
        icon: "pi pi-file",
        to: "/report/productdetailgroupreport",
        name: "productdetailgroupreport",
        children: [],
      },
      {
        title: "รายงานรายละเอียดสินค้า ตามหมวด",
        icon: "pi pi-file",
        to: "/report/productdetailcatrgoryreport",
        name: "productdetailcatrgoryreport",
        children: [],
      },
      {
        title: "รายงานบาร์โค้ดสินค้า",
        icon: "pi pi-file",
        to: "/report/productbarcodereport",
        name: "productbarcodereport",
        children: [],
      },
      {
        title: "รายงานราคาขายสินค้า",
        icon: "pi pi-file",
        to: "/report/productsalepricereport",
        name: "productsalepricereport",
        children: [],
      },
      {
        title: "รายงานราคาขายสินค้า ตามบาร์โค๊ด",
        icon: "pi pi-file",
        to: "/report/productsalebarcodereport",
        name: "productsalebarcodereport",
        children: [],
      },
      {
        title: "รายงานสินค้าคงเหลือ ",
        icon: "pi pi-file",
        to: "/report/product",
        name: "inventoryReport",
        children: [],
      },
      {
        title: "รายงานเคลื่อนไหวสินค้า ",
        icon: "pi pi-file",
        to: "/report/product",
        name: "productMoveReport",
        children: [],
      },
      {
        title: "รายงานรายละเอียดลูกค้า ",
        icon: "pi pi-file",
        to: "/report/product",
        name: "CusdetailReport",
        children: [],
      },
      {
        title: "รายงานการขายสินค้า ",
        icon: "pi pi-file",
        to: "/report/product",
        name: "ProductsaleReport",
        children: [],
      },
      {
        title: "รายงานการรับเงิน ",
        icon: "pi pi-file",
        to: "/report/product",
        name: "paidReport",
        children: [],
      },
      {
        title: "รายงานกำไรขั้นต้น ",
        icon: "pi pi-file",
        to: "/report/product",
        name: "GrossProfitReport",
        children: [],
      },
      //Report End
    ],
  },
];
